### ISSUE TITLE
不支持datetime类型 

### ISSUE THREAD

**Issue by pondered** [hongque-pro/infra-orm#2]
com.labijie.orm.generator.DefaultValues

这个类的数据被写死了，没有对 datetime 映射

https://jetbrains.github.io/Exposed/data-types.html

**Comment by endink** [comment]
`2.0.4` 已经支持下列类型：

- date
- time
- datetime 
- timestamp 
- duration    

虽然这些类型受到支持，不得不说，这不是普遍适用的高性能数据库准则，通常我们使用 `long` 代替这些类型以获得更好的数据库查询性能。
