### ISSUE TITLE
虽然支持序列化 但是不支持 自定义序列化

### ISSUE THREAD

**Issue by pondered** [hongque-pro/infra-orm#3]
例如我使用 kotlinx.serialization 但是无法对 bigdecimal 进行序列化
这时候使用 `@KspTablePojo(kotlinSerializable = true)`也是不行的，反而会报错

**Comment by endink** [comment]
kotlinx.serialization 不是太熟悉，一般都用 jackson， BigDecimal 需要自定义序列化, 请参考这里：

https://stackoverflow.com/questions/75257762/how-can-i-json-encode-bigdecimal-and-biginteger-in-kotlinx-serialization-without

close here!

**Comment by pondered** [comment]
但是 生成器不支持 生成 jackson 注解。。

**Comment by endink** [comment]
一般情况下 jackson 无需注解即可序列化，应用层都会提供独立的另一套 pojo，这是数据层实体,很少有序列化需求，也不会直接用做API返回，所以你的需求我们几乎都没有遇到
